on: [ push, workflow_dispatch ]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Write Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM ubuntu:latest
          WORKDIR /app
          COPY . .
          RUN apt-get update && apt-get install -y \
              python3 \
              python3-pip
          CMD ["python3", "app.py"]
          EOF

      - name: Build the image
        run: docker build -t $IMAGE_NAME .

      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.5
        with:
          pcc_console_url: https://us-east1.cloud.twistlock.com/us-2-158286553
          pcc_user: fe84e279-5618-4fb0-a231-7308ed8b46a4
          pcc_pass: fC/kwCY46umqfw0UePfDQbAifro=
          image_name: ${{ env.IMAGE_NAME }}

      # (Optional) for compatibility with GitHub's code scanning alerts
      - name: Upload SARIF file
        if: ${{ always() }} # necessary if using failure thresholds in the image scan
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif_file }}
